# Generated by Django 3.2.4 on 2021-11-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='data_creazione',
            field=models.DateField(auto_now_add=True),
        ),
    ]
