# Generated by Django 3.2.4 on 2021-11-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_postmodel_data_creazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
