# Generated by Django 3.2.4 on 2021-11-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211122_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='stato',
        ),
    ]
