# Generated by Django 3.2.9 on 2021-11-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_comment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='argomento',
            field=models.CharField(choices=[('Crypto', 'Crypto'), ('Adesso nel mondo', 'Adesso nel mondo'), ('Economia', 'Economia'), ('Tecnologia', 'Tecnologia')], max_length=70),
        ),
    ]
